version: 1.7.{build}
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  my_variable:
    secure: Qpq/4cyuTUzmt/r4HsQxioG6WXrZSK3mzVq5iUJC2RI=
  NugetApiKey:
    secure: Ar6IQ+BxCwH6r8SgUB+6wzlWRD0Y+pkW+eFhZUTsF/yb5SyfEcDV7RNzzbGGe26Y
  ChocolateyApiKey:
    secure: klwi3/bn7RRe4vsqMat7GNNaD1kToVyewIAD5MPSptorqJZbySOF6wio/KW9SYza
  GitHubApiKey:
    secure: N83nQZ/QQVqpRnl0D6F/xSbKjn062y07JdskpUpbWryMY2JDo4Be9lUXmob+xcOO
build_script:
- cmd: PowerShell.exe -NoProfile -ExecutionPolicy Bypass -Command "& '.\build.ps1' --target Clean Publish ChangeVersionNumber --Configuration Release"
test: off
artifacts:
- path: bin\Release\
  name: Release-files
- path: bin\**\*.zip
- path: bin\**\*.nupkg
